export {
  default,
  callApi,
  normalizeApiResponse,
  executeOperation,
  getVisitList,
  getVisitDetails,
  addVisit,
  editVisit,
  startVisit,
  checkOutVisit,
  completeVisit,
  cancelVisit,
  missVisit,
  approveVisit,
  getErpCustomers,
  getShowRooms,
  getProjectMaster,
  getNearestTarget,
  getTargets,
  getTargetTypes,
  getPurposes,
  addTarget,
  editTarget,
  deleteTarget,
  getUsers,
  addUser,
  editUser,
  deleteUser,
  getTeams,
  addTeam,
  editTeam,
  deleteTeam,
  getPermissions,
  addPermission,
  editPermission,
  deletePermission,
  getSurveyTemplates,
  getSurveyTemplateDetails,
  saveSurveyTemplate,
  deleteSurveyTemplate,
  submitSurvey,
  getSurveyAnswers,
  getSalespersons,
  getMerchantUsers,
  getDashboardKPI,
  getSalespersonKPI,
  getMerchantKPI,
  getCompetitorKPI,
  saveVisitAttachment,
  deleteVisitAttachment,
  saveVisitFollowUpTask,
  deleteVisitFollowUpTask,
  saveVisitCompetitorInfo,
  deleteVisitCompetitorInfo,
  saveVisitDisplayInspection,
  getSurveyDashboardData,
} from '../services/API'

import { executeOperation } from '../services/API'

// Backwards compatibility with any components calling the generic apiCall
export async function apiCall(operation, lineData = {}, user = 'admin') {
  return executeOperation(operation, {
    LineData: JSON.stringify(lineData),
    User: user,
  })
}

